# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reget < Formula
  desc "Download a specific or latest release/tag from github based on the API"
  homepage "https://github.com/januznl/reget"
  version "0.0.7"
  license "MIT"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Januznl/reget/releases/download/v0.0.7/reget_Linux_arm64.tar.gz"
      sha256 "d254e15843c034088d384e5c78da6a52da93ba0c8c730cba4f8f1e44fe7493cd"

      def install
        bin.install "reget"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Januznl/reget/releases/download/v0.0.7/reget_Linux_armv6.tar.gz"
      sha256 "a9be021f592c1e11360d415fbee1becb089c2169478b1d05e87fa384534e0b5f"

      def install
        bin.install "reget"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Januznl/reget/releases/download/v0.0.7/reget_Linux_x86_64.tar.gz"
      sha256 "e8da1a350869962eae6383431d559fe24d06f90afeae980632579dc59ea6ad66"

      def install
        bin.install "reget"
      end
    end
  end

  test do
    system "#{bin}/reget -v"
  end
end
